### ISSUE TITLE
Breadcrumbs in API docs show the package name twice

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#1522]
It looks like our API docs breadcrumbs have somehow lost the "API Docs" label in the breadcrumb and are instead showing the name of the package twice:

![image](https://user-images.githubusercontent.com/274700/191377827-5b65a541-2e7e-4784-8045-37bc87a3f1a6.png)

I believe the the second instance should be "API Docs".

**Comment by susanev** [comment]
@kimberleyamackenzie any immediate thoughts on what happened here?

**Comment by kimberleyamackenzie** [comment]
No conclusive discoveries because I am having trouble with getting all the things right with my local set up w/ API docs loaded, but seems like somewhere the link title property was changed, since that ought to be what this is reading from.  I can poke more into this tomorrow when I get my set up sorted.
