### ISSUE TITLE
Failed to Download for Our Custom Resource

### ISSUE THREAD

**Issue by burakgzt** [pulumi/registry#2079]
### What happened?

We created our Provider and its released on PyPI and Pulumi Registry. When we try to do `pip install pulumi-nuage==0.0.4` we are getting the following error

```
File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['pulumi', 'plugin', 'install', 'resource', 'nuage', '0.0.4']' returned non-zero exit status 255.
```

To investigate the error more, we run this command manually `pulumi plugin install resource nuage 0.0.4`, and this one is causing the following error:
```
error: [resource plugin nuage-0.0.4] downloading from : failed to download plugin: nuage-0.0.4: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-nuage-v0.0.4-darwin-arm64.tar.gz
```

version 0.0.4 is published here https://www.pulumi.com/registry/packages/nuage/
What could be the issue?

### Expected Behavior

It should download the plugin

### Steps to reproduce

Running `pip install pulumi-nuage==0.0.4`  or `pulumi plugin install resource nuage 0.0.4`

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @burakgzt, the reason `pulumi plugin install resource nuage 0.0.4` doesn't work is because the github repository is from a third-party organisation https://github.com/nuage-studio, not `https://github.com/pulumi` in that case, you should specify the `pluginDownloadURL` property in the [schema file](https://github.com/nuage-studio/pulumi-nuage/blob/master/schema.json) and set it to `"github://api.github.com/nuage-studio"`

It should work manually using 
```
pulumi plugin install resource nuage 0.0.4 --server github://api.github.com/nuage-studio
```
but really this should be automatic from the generated SDKs if you have `pluginDownloadURL` defined.
