### ISSUE TITLE
404 response to how to guide for azure ts functions

### ISSUE THREAD

**Issue by mastoj** [pulumi/registry#219]
I did a search on google for "create azure function pulumi" and the first hit is: https://www.pulumi.com/registry/packages/azure/how-to-guides/azure-ts-functions/

That is all good that it shows at top, but the sad part is that the url returns 404 at the moment. Not sure if it intended or a bug.

**Comment by susanev** [comment]
@mastoj apologies for this issue, and thank you for reporting!!

to access the guide pls use this link: https://www.pulumi.com/registry/packages/azure-native/how-to-guides/azure-ts-functions/

we will look into getting the link you hit from google working correctly.

**Comment by djgrove** [comment]
@mastoj Have verified this is fixed. The original URL was https://www.pulumi.com/docs/tutorials/azure/how-to-guides/azure-ts-functions, and our redirect rules were erroneously taking you to https://www.pulumi.com/registry/packages/azure/how-to-guides/azure-ts-functions/ instead of https://www.pulumi.com/registry/packages/azure-native/how-to-guides/azure-ts-functions/. Our Azure and Azure Native tutorials were previously sharing a directory namespace, and this is no longer the case.

Thank you for using Pulumi and for the issue report.

**Comment by djgrove** [comment]
@mastoj thank you for the report and for using Pulumi.

We ran into this issue because our redirect rules were mapping all guides from /docs/tutorials/azure to registry/packages/azure/how-to-guides which is why you were directed to the wrong path. Some of these guides were Azure Native guides and were since moved to registry/packages/azure-native to be more specific, so we've updated the redirect rules to allow for these cases. I've confirmed that https://www.pulumi.com/docs/tutorials/azure/azure-ts-functions/ now redirects you to the correct path.
