### ISSUE TITLE
Generate Pulumi Package API documentation inside the repository

### ISSUE THREAD

**Issue by infin8x** [pulumi/registry#223]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Today, the API documentation for a Pulumi Package is generated and published in https://github.com/pulumi/docs. As part of #222 and in preparation for #206, we should enable a Pulumi Package's API documentation to be generated and stored inside the package's repository, ideally as part of any build and publish processes/scripts/workflows we provide.

**Comment by EvanBoyle** [comment]
@praneetloke can you write up the plan here for what needs to happen?

**Comment by praneetloke** [comment]
Uhh yeah re-reading the description and this issue is not what we are looking to do. I totally missed this part:

> we should enable a Pulumi Package's API documentation to be generated and stored inside the package's repository

That would be quite an under-taking and would require us to spend more time as a team thinking about that. I am going to delete my original comment and open a separate issue. It'll be for solving the spread of package documentation between the `registry` and the `docs` repos as an immediate problem.

**Comment by iwahbe** [comment]
We don't want to go in this direction anymore. We believe that the package should be responsible for serving a schema, and the registry should be responsible for transforming that schema into docs pages.
