### ISSUE TITLE
cloudflare.ruleset inconsistency in naming RulesetRule vs RulesetRuleArgs

### ISSUE THREAD

**Issue by interurban** [pulumi/registry#2924]
Customer docs issue reported: Quirk in the docs: cloudflare.Ruleset claims it requires a list of RulesetRuleArgs in the rules field, but that type isn't defined at all. There are various types listed in the supporting types section, but none of them match the requirement listed in the docs.

The docs issue to highlight is the inconsistency in naming - RulesetRule vs RulesetRuleArgs. https://www.pulumi.com/registry/packages/cloudflare/api-docs/ruleset/#rulesetrule

**Comment by cnunciato** [comment]
I'm definitely in unfamiliar waters here, but it looks like this is a codegen issue -- or at least that's where these "Args" suffixes values appear to be coming from.

Here's a pulumi/pulumi PR that tweaks a few values in the Node, Python, Go, and .NET SDKs to make this a little more clear -- search for `Argsfoo`:

https://github.com/pulumi/pulumi/pull/13614/files

And here's a docs preview build that uses this PR branch to build out the API docs:

* [cloudflare.Ruleset](http://www-pulumi-docs-origin-pr-9573-b52c83d1.s3-website.us-west-2.amazonaws.com/registry/packages/cloudflare/api-docs/ruleset/)
* [aws.kms.Grant](http://www-pulumi-docs-origin-pr-9573-b52c83d1.s3-website.us-west-2.amazonaws.com/registry/packages/aws/api-docs/kms/grant/)

It looks like this issue is pretty much everywhere -- in [aws.s3.Bucket](http://www-pulumi-docs-origin-pr-9573-b52c83d1.s3-website.us-west-2.amazonaws.com/registry/packages/aws/api-docs/s3/bucket/#inputs), etc. I admit I never really noticed until now, but there it is.

What I don't understand is whether this is a purely a docs issue or something bigger. Given where this code lives (in `github.com/pulumi/pulumi/pkg/codegen`, but outside of `docs`) and all the logic around it, I suspect any changes here would impact more than just to the API docs.

@lukehoban do you have any suggestions or guidance for us? Maybe point me to someone I can follow up with?

**Comment by lukehoban** [comment]
Yes - this issue is on every Python api docs page. 

@danielrbradley captures the issue in his comment here: https://github.com/pulumi/registry/issues/1524#issuecomment-1253536957

The codegen itself is “correct”, but the name of the type is different in input and output positions. That leads to the way we use these types in the docs being confusing, since in some places we use the input name and in others the output name. 

It’s not clear exactly what fix would be best for this - since these types can be referenced in both input and output forms. We may have to - for Python- make the title of the supporting types section list both the with and without Args suffix versions - since there could be references to it with either name (for usage as an input or output). 

That change would be in docs codegen - in a sibling folder to the language SDK codegen at https://github.com/pulumi/pulumi/tree/master/pkg/codegen/docs.

**Comment by cnunciato** [comment]
Ok thanks, I'll dig in there and see what I can find.

>Yes - this issue is on every Python api docs page.

In case it's relevant, this shows up for every language, not just Python:

![image](https://github.com/pulumi/registry/assets/274700/484b1050-0489-4588-81fb-d8f61c9c9757)

**Comment by cnunciato** [comment]
Ok, I think I get it now. To address this, we should: 

* Only use the `Args` suffix for Python, and only in input contexts
* Indicate (again only for Python) that the `Args` version is also valid and comprised of the same members

I think that should do it -- let me know if that's at all wrong or incomplete.
