### ISSUE TITLE
remove cloud providers from left nav in docs

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#311]
## overview
on 12/04 we should evaluate whether there is significant usage of the cloud providers item in the left nav in docs (which sends you to registry) and if there is not we should remove it.

**Comment by susanev** [comment]
we did not add appropriate tracking for this link until https://github.com/pulumi/pulumi-hugo/pull/827 which merged on 11/04, so ive adjusted the date to evaluate to 12/04

**Comment by susanev** [comment]
@kimberleyamackenzie assigning you here as well, to help us figure out if its good to remove this now after looking at the data.

**Comment by kimberleyamackenzie** [comment]
Looks like the cloud providers link has been clicked about 1800 times since it was added on November 4th (based on [Google Analytics](https://analytics.google.com/analytics/web/#/report/content-event-events/a116166038w172505890p172019141/_u.date00=20211104&_u.date01=20220127&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22toc-cloud-providers%22,0%5D%5D&explorer-table.rowCount=500&_r.drilldown=analytics.eventCategory:User%20Interaction,analytics.eventAction:link-click&explorer-table-dataTable.sortColumnName=analytics.eventLabel&explorer-table-dataTable.sortDescending=true/) and [Metabase](https://metabase.corp.pulumi.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MTkyLCJmaWx0ZXIiOlsiYW5kIixbImNvbnRhaW5zIixbImZpZWxkIiwzODgzLG51bGxdLCJ0b2MtY2xvdWQtcHJvdmlkZXJzIix7ImNhc2Utc2Vuc2l0aXZlIjpmYWxzZX1dXSwiYWdncmVnYXRpb24iOltbImNvdW50Il1dfSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5Ijoic2NhbGFyIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) - which have slightly different counts).

A couple comparison points:  "Download and install" has about 1500 clicks over the same period, "API reference" has 2300.  Average across all links we track is around 2000.  The [total clicks of any item in that left hand nav](https://metabase.corp.pulumi.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE5MiwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJmaWx0ZXIiOlsiYW5kIixbImNvbnRhaW5zIixbImZpZWxkIiwzODY4LG51bGxdLCItdG9jLSIseyJjYXNlLXNlbnNpdGl2ZSI6ZmFsc2V9XV19LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InNjYWxhciIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUucGl2b3QiOmZhbHNlfSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=) over the period is around 70,000. 

I tried to drill down into the paths folks follow + drop-offs (so, do people click on "Cloud providers" expecting something else, and immediately leave or navigate back to docs?) but wasn't able to as easily get that info.  But can poke more into it if we think it would be helpful! 

what do you think @susanev ? Based on those numbers alone, I'd say we keep it.  I can also get more data if there's other points that would be helpful to consider.

**Comment by susanev** [comment]
yaah thats a lot. lets keep it for now. ill put this back on the backlog for us to review again later in the year.
thx for checking out the data for this!!

**Comment by cnunciato** [comment]
Thanks for grabbing that data, that's great! 

Y'all might find this interesting, too, as it's related. [This query](https://metabase.corp.pulumi.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzcsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsMzg1LG51bGxdLCIvcmVnaXN0cnkvIl0sWyJzdGFydHMtd2l0aCIsWyJmaWVsZCIsMzkzLG51bGxdLCJodHRwczovL3d3dy5wdWx1bWkuY29tIix7ImNhc2Utc2Vuc2l0aXZlIjpmYWxzZX1dLFsidGltZS1pbnRlcnZhbCIsWyJmaWVsZCIsNDA5LG51bGxdLC05MCwiZGF5Iix7ImluY2x1ZGUtY3VycmVudCI6dHJ1ZX1dXSwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJicmVha291dCI6W1siZmllbGQiLDM5MyxudWxsXV0sIm9yZGVyLWJ5IjpbWyJkZXNjIixbImFnZ3JlZ2F0aW9uIiwwXV1dfSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=) ranks internal raw referrals to /registry (from anywhere on the website) over the last 90 days, and shows that the Docs home page is the #2 source of internal traffic to that page, only a bit behind the pulumi.com home page. That tells me that not only are people still clicking that Cloud providers link, but a majority of them are also doing so from the Docs home page -- i.e., they're clicking Docs, then either Registry from the main nav or Cloud Providers from the left-hand nav (as I don't think there are any other links to the Registry on that page, other than in the footer).

**Comment by susanev** [comment]
we are doing a redesign of the docs landing page this quarter, so we can possibly include easy access to registry from that page in that work.
