### ISSUE TITLE
Copy complete `docs` folder from community packages

### ISSUE THREAD

**Issue by ringods** [pulumi/registry#3159]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The new OVH provider contains a migration guide in the `docs` folder of the upstream repository:

https://github.com/ovh/pulumi-ovh/tree/main/docs

The `how-to-guides` folder is not copied to the `registry` repo here:

https://github.com/pulumi/registry/tree/master/themes/default/content/registry/packages/ovh

### Affected area/feature

Additional documentation besides the `_index.md` and `installation-configuration.md` files.

Related: #3133

**Comment by ringods** [comment]
cc: @scraly

**Comment by scraly** [comment]
Any news? :) 
Thanks

**Comment by ringods** [comment]
@tmeckel I leave this for our docs team to chime in.

**Comment by cnunciato** [comment]
@tmeckel Thanks for filing this issue and apologies for the delayed response. 

We'd definitely love to make it possible for you to add docs like these to the Registry, and supporting how-to guides is an excellent idea! But for now, because of some changes we have planned for the way we render pages (including How-to guides) in the Registry, you'll need to use the Overview doc for this. I took a look at your migration guide and dropped in as a second-level heading to give you an idea how this would look:

https://github.com/pulumi/registry/pull/3246/files#diff-e632aef8a69c0a7fa0b4ccebdfb057261a906c9b8bdf70d31e87cb6ab6154fd6R113

Preview link: 
http://registry--origin-pr-3246-9be2f947.s3-website.us-west-2.amazonaws.com/registry/packages/ovh/

Hopefully this is an acceptable option for you. Let us know.

**Comment by tmeckel** [comment]
@cnunciato Thanks for the quick review of the issue. My problem is that I've to publish the following list of (howto) guides from the upstream Terraform provider to the Pulumi registry in some manageable way.

![image](https://github.com/pulumi/registry/assets/14177833/1884ef8a-0281-4e14-a530-ee8f1b737327)

Squeezing all these documents into a single document, even if you can of course divide it with chapter headings, is from my point of view not really user-friendly.

I know that I'm early again with my pull request 😁 , and I don't know what great new features you have planned, but it would be nice if we could find a solution to this problem in the short term.

**Comment by cnunciato** [comment]
>it would be nice if we could find a solution to this problem in the short term.

I hear you, and again I love the idea of supporting guides like these for community packages. But alas, this is what we have for now. Our near-term plan is to remove these "how-to" pages from the Registry and move them to another area of the site, as well as to explore alternatives to building the Registry statically with Hugo, and this particular approach wouldn't really align with either of those plans, unfortunately.

I do think the Overview page should work just fine for this, though; I took a look through your content, and our on-this-page navigation should more than suffice for handling these docs as individual subsections. We have plenty of lengthy pages in our docs that rely on this navigation, in fact, so it ought to work pretty well for this too, at least for the time being.

I'd therefore propose that we close this issue and file another for supporting tutorials for community packages generally, as I'd really like us to be able to do this too. Thank you again for the suggestion! I'm happy to file this issue for you if you like.

**Comment by tmeckel** [comment]
@cnunciato Thanks for the good explanation why currently no other way than via the two Markdown documents for community providers is possible. Because I personally didn't open this issue I can't decide on closing it. @ringods opened it because of an issue raised by @scraly while providing documentation for the OVH provider, as stated in the initial description of the issue. 

What I will do though, is to close the connected PR https://github.com/pulumi/registrygen/pull/19 in the `registrygen` tool.

**Comment by cnunciato** [comment]
@ringods Any opposition to closing this, then?

**Comment by ringods** [comment]
@cnunciato no opposition. Out of curiosity, is there any other GH issue we can track on the future plans to support "extra" package content?

**Comment by cnunciato** [comment]
Sorry for the delay -- here's that issue: https://github.com/pulumi/registry/issues/3391

Feel free to comment, suggest, etc., anything you like. Thanks for the discussion all!
