### ISSUE TITLE
Create EMR cluster and Task Nodes Fleet simultaneously

### ISSUE THREAD

**Issue by weiucla** [pulumi/registry#3189]
The current interface provided by Pulumi can only start creating task nodes after the EMR cluster is created using either `aws.emr.InstanceGroup` or `aws.emr.InstanceFleet`. Why can't Pulumi provide a parameter like `task_instance_fleet` similar to `master_instance_fleet` or `core_instance_fleet` as part of `aws.emr.Cluster`?

Our project is using Pulumi for launching EMR clusters with task nodes. The way that Pulumi launches task nodes only after cluster is created significantly slows down the whole process. Would like to understand why the interface is like this way, and if it can be modified as I suggested above to improve the cluster launching experience with task nodes.

File: [themes/default/content/registry/packages/aws/api-docs/emr/cluster/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/emr/cluster/)

**Comment by cnunciato** [comment]
@weiucla I'm definitely no expert in EMR, but it looks like this is because AWS needs to know what cluster to associate these nodes with, which implies the cluster needs to exist (and have an ID) before the nodes can be created. The CLI docs seem to confirm this: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-instance-fleet.html#emr-task-instance-fleet

```
aws emr add-instance-fleet --cluster-id <cluster-id> [...] 
``` 

Does this answer your question?

**Comment by weiucla** [comment]
@cnunciato Thanks for the answer. Task nodes can be attached to an existing EMR cluster where cluster id needs to be provided, as you mentioned above. But task nodes can also be created at the same time when the EMR cluster is created - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr/client/run_job_flow.html
```
'InstanceRole': 'MASTER'|'CORE'|'TASK',
```
Looks like Pulumi is missing the 2nd use case.
