### ISSUE TITLE
API Docs for Okta:User misrendered

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/registry#4856]
### What happened?

Visit https://www.pulumi.com/registry/packages/okta/api-docs/user/user/ and observe the page rendered sideways.

### Example

The truth is in the pudding here.

### Output of `pulumi about`

n/a

### Additional context

It is very likely that the schema for Okta:User is sending badly formatted data. However, the misrendering should never happen. We should prefer to not render rather than have the page look as it does today.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by sean1588** [comment]
thanks @guineveresaenger for filing this. Doing some poking around, I suspect this may be due to the markdown example code headings being embedded in the code block. Looks like this was an accident on their part. I suspect this may affect the way the page is parsed, but could be wrong here. 


https://github.com/okta/terraform-provider-okta/blob/master/docs/resources/user.md?plain=1#L14

![Image](https://github.com/pulumi/registry/assets/16751381/5e25e983-54f3-4880-b5f0-63002fcdfc53)

**Comment by sean1588** [comment]
I opened a PR in the upstream to fix up the markdown.

**Comment by sean1588** [comment]
resolved by: https://github.com/pulumi/pulumi-snowflake/issues/683
